### ISSUE TITLE
Only Brings up Gmail

### ISSUE THREAD

**Issue by beanboots** [stadler/SendPage#7]
Have been using SendPage for over a year, it always bought up WLM email, in the past week it will only bring my Gmail Account. Whats gone wrong, and how do I fix it?

**Comment by stadler** [comment]
Hey
Nice to hear that you enjoy SendPage.
I guess that your changed your mailto protocol handler to gmail. Because what sendpage does is basically only open a mailto:name@example.com link. The program (handler) you have associated to this protocol is defined in your operating system. How you can change the mailto handler within chrome can be found here:
* Chrome: https://support.google.com/chrome/answer/1382847?hl=de

I hope this helps.

I will keep this issue open as an idea on how SendPage could be extended in future.

**Comment by beanboots** [comment]
Hi,
Thanks for the reply, it now seems to be working OK again. Who knows what goes on iinside my machine!
